### ISSUE TITLE
what is `m` gate?

### ISSUE THREAD

**Issue by qci-amos** [microsoft/qiskit-qir#25]
https://github.com/microsoft/qiskit-qir/blob/89505330aabb5216b5565b677f46d468c87ce786/src/qiskit_qir/visitor.py#L20

I don't think [Qiskit ](https://qiskit.org/documentation/stubs/qiskit.circuit.QuantumCircuit.html) has a gate `QuantumCircuit.m`...

**Comment by idavis** [comment]
@qci-amos It is a alias for measure which maps to mz or measure depending on allocation mode. This is no longer used in the latest pyqir release.
