### ISSUE TITLE
preserve `barrier` in QIR

### ISSUE THREAD

**Issue by qci-amos** [microsoft/qiskit-qir#26]
### Description

Currently, `barrier` is a no-op:
https://github.com/microsoft/qiskit-qir/blob/89505330aabb5216b5565b677f46d468c87ce786/src/qiskit_qir/visitor.py#L233-L234

However, `barrier` is required for many kinds of characterization circuits. For example, without a `barrier` instruction, randomized benchmarking would collapse into a no-op! By removing it here, the user's requirements are lost.

**Comment by christian512** [comment]
@idavis: I think the issue is not solved yet.
The code linked above is still the same and `barrier` is still unsupported.
