### ISSUE TITLE
Update `pyqir` dependecy to support macOS with M1 processors

### ISSUE THREAD

**Issue by jond01** [microsoft/qiskit-qir#34]
* qiskit-qir version: 0.2.0 (and today's main)
* Python version: 3.8
* Operating System: macOS with an ARM processor (M1)

### Description

Following https://github.com/qir-alliance/pyqir/issues/101#issuecomment-1343254900 and [pyqir v0.7.0 release](https://github.com/qir-alliance/pyqir/releases/tag/v0.7.0), `qiskit-qir` can support macOS with M1 processors.
To achieve this, the fixed requirement on `pyqir` has to be updated or relaxed:
https://github.com/microsoft/qiskit-qir/blob/f997d88f8f18dcecbedcb9cb4364961a36d0a9dc/setup.cfg#L33

---

Also, it's probably desirable to replace `pyqir-generator` with `pyqir`:

> ### `pyqir-generator` has been replaced by `pyqir`
>
> Please install the `pyqir` package instead, which provides the same functionality.
> Read the [upgrade guide](https://www.qir-alliance.org/pyqir/upgrade.html) for help with upgrading from `pyqir-generator` 0.6.

https://pypi.org/project/pyqir-generator/

**Comment by idavis** [comment]
@jond01 - #32 should address what you've outlined. We're moving to PyQIR 0.8

**Comment by idavis** [comment]
@jond01 Can you please try 0.3.1 which is now available on pypi? The API has change to `to_qir_module` allowing you to work with the module, get its bitcode, or IR as you wish.

**Comment by jond01** [comment]
Great, thanks! The main thing left is propagating this update further to the `azure-quantum` package: https://github.com/microsoft/qdk-python/issues/410.
